<?php

return [
    'email' => [
        'title' => 'E-Mail adresse bearbeiten.',
        'updated' => 'Deine E-Mail wurde geändert.',
    ],
    'password' => [
        'title' => 'Passwort ändern',
        'requirements' => 'Your new password should be at least 8 characters in length.',
        'updated' => 'Dein Passwort wurde geändert.',
    ],
    'two_factor' => [
        'button' => 'Configure 2-Factor Authentication',
        'disabled' => 'Two-factor authentication has been disabled on your account. You will no longer be prompted to provide a token when logging in.',
        'enabled' => 'Two-factor authentication has been enabled on your account! From now on, when logging in, you will be required to provide the code generated by your device.',
        'invalid' => 'The token provided was invalid.',
        'setup' => [
            'title' => 'Setup two-factor authentication',
            'help' => 'Can\'t scan the code? Enter the code below into your application:',
            'field' => 'Enter token',
        ],
        'disable' => [
            'title' => 'Disable two-factor authentication',
            'field' => 'Enter token',
        ],
    ],
];
